server:
  port: ${SERVER_PORT:${PORT:8080}}
spring:
  application:
    name: ${APP_NAME:MediSalud-Scheduling}
  devtools:
    add-properties: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,prometheus}
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}
